'use client';

import Image from 'next/image';
import { useTranslations } from 'next-intl';

export default function Footer() {
  const t = useTranslations();
  return <footer id="contact" className="bg-primary-deep py-14 text-white"><div className="container-custom"><div className="grid gap-10 md:grid-cols-[1.2fr_.8fr_.8fr] md:items-start"><div><p className="floating-label mb-4">Contact</p><h2 className="mb-6 text-3xl font-black">{t('Contact.sectionTitle')}</h2><div className="flex flex-col gap-3 text-white/75"><a href="https://wa.me/966505684505" target="_blank" rel="noopener noreferrer" className="w-fit font-bold transition-colors hover:text-accent ltr">{t('Contact.phone')}</a><a href="mailto:feoozee@hotmail.com" className="w-fit font-bold transition-colors hover:text-accent ltr">{t('Contact.email')}</a><p className="font-bold">{t('Contact.location')}</p></div></div><div><h3 className="mb-5 text-lg font-black text-accent">{t('Footer.quickLinks')}</h3><nav className="flex flex-col gap-3 font-bold text-white/70"><a href="#about" className="hover:text-accent">{t('Navigation.about')}</a><a href="#experience" className="hover:text-accent">{t('Navigation.experience')}</a><a href="#certificates" className="hover:text-accent">{t('Navigation.certificates')}</a></nav></div><div className="flex items-start gap-4"><div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-full border-2 border-accent"><Image src="/images/avatar.jpg" alt={t('Header.name')} fill className="object-cover" /></div><div><h3 className="text-lg font-black">{t('Header.name')}</h3><p className="mt-2 text-sm font-bold leading-relaxed text-white/60">{t('Header.title')}</p></div></div></div><div className="mt-12 flex flex-wrap justify-between gap-3 border-t border-white/15 pt-6 text-xs font-bold text-white/45"><p>{t('Footer.rights')}</p><a href="https://wa.me/6282125277889" target="_blank" rel="noopener noreferrer" className="text-accent hover:text-white">{t('Footer.designBy')} @ أدهم بوقس</a></div></div></footer>;
}
